CREATE DATABASE IF NOT EXISTS zaakpay_checkout CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE zaakpay_checkout;

CREATE TABLE IF NOT EXISTS payment_orders (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  order_id VARCHAR(64) NOT NULL UNIQUE,
  customer_name VARCHAR(120) NOT NULL,
  customer_email VARCHAR(190) NOT NULL,
  customer_phone VARCHAR(25) NOT NULL,
  amount_paise INT NOT NULL DEFAULT 49900,
  status ENUM('CREATED','SUCCESS','FAILED','CANCELLED') NOT NULL DEFAULT 'CREATED',
  zaakpay_txn_id VARCHAR(128) NULL,
  response_code VARCHAR(20) NULL,
  gateway_message TEXT NULL,
  callback_payload JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  paid_at TIMESTAMP NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
